name: e_learning
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # localization plugins
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0

  # Flutter Conditions widget
  flutter_conditional_rendering: ^2.0.0

  # Bloc
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1

  # Network
  dio: ^4.0.0
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.1

  # Memory & cache
  shared_preferences: ^2.0.6

  # pdf
  syncfusion_flutter_pdfviewer: ^19.2.62-beta
  path_provider: ^2.0.4
  http: ^0.13.3
  open_file: ^3.2.1

  # Images
  image_picker: ^0.8.4+1
  multi_image_picker2: ^5.0.2
  flutter_absolute_path:
    git:
      url: https://github.com/kornperkus/flutter_absolute_path
  path: ^1.8.0

  # animations
  animations: ^2.0.2
  flutter_staggered_animations: ^1.0.0

  # UI
  smooth_page_indicator: ^1.0.0+2
  fluttertoast: ^8.0.7
  flutter_card_swipper: ^0.4.0
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  font_awesome_flutter: ^9.1.0
  tab_indicator_styler: ^2.0.0
  buttons_tabbar: ^1.3.1
  flutter_screenutil: ^5.0.0+2
  lottie: ^1.2.1
  pin_code_fields: ^7.3.0
  progress_state_button: ^1.0.3
  im_stepper: ^0.1.3
  flutter_rating_bar: ^4.0.0
  duration_picker: ^1.0.1
  flutter_progress_hud: ^2.0.0
  pull_to_refresh: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  date_picker_timeline: ^1.2.3
  timelines: ^0.1.0
  like_button: ^2.0.3
  flutter_linkify: ^5.0.2
  flutter_statusbarcolor_ns: ^0.4.0
  focused_menu: ^1.0.5
  flutter_slidable: ^1.1.0
  animated_splash_screen: ^1.1.0

  # Youtube Video Player
  youtube_player_flutter: ^8.0.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To teacher_add_student assets to your application, teacher_add_student an assets section, like this:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To teacher_add_student custom fonts to your application, teacher_add_student a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # english
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 400

    - family: NeoSansArabic
      fonts:
        - asset: assets/fonts/NeoSansArabic.ttf
        - asset: assets/fonts/NeoSansArabicMedium.ttf
          weight: 600

    - family: MyIcons
      fonts:
        - asset: assets/icons/MyIcons.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
